### ISSUE TITLE
Can't add, edit or delete products to/from orders in admin, no any error message (bluehost)

### ISSUE THREAD

**Issue by o4itea** [opencart/opencart.github.io#332]
I have the same problem which is products not showing up when I add, edit or delete in Sale->Orders in admin section (json get response empty from api/cart/products) and without getting any error message.

gif video of issue (http://o4itea.com/add-edit-delet.gif)
response in console (http://o4itea.com/sale-order.jpg)

Actually, this problem does not exist with WAMP(local sarver) or goddady .com host but only when I use bluehost .com host. (php 7.2)

Can you please help me
https://alorood.com/test/admin/index.php?route=sale/order/edit&order_id=1
user: user
pass: pass

_Originally posted by @o4itea in https://github.com/opencart/opencart/issues/7500#issuecomment-626231176_

**Comment by danielkerr** [comment]
which opencaRT VERSION

**Comment by o4itea** [comment]
3.0.3.2 and 3.0.3.3
